### ISSUE TITLE
IllegalStateException: RequestQueue not Initialized

### ISSUE THREAD

**Issue by marz-dwr** [ogrebgr/android_volley_examples#15]
Why does it return the exception? I've followed through your codes.

Logs
`Caused by: java.lang.IllegalStateException: RequestQueue Not Initialized
                      at com.capstone.artink.app.CustomVolley.getRequestQueue(CustomVolley.java:29)
                      at com.capstone.artink.Dashboard.onCreate(Dashboard.java:101)
                      at android.app.Activity.performCreate(Activity.java:5008)
                      at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1079)
                      at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2023)
                      at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2084) 
                      at android.app.ActivityThread.access$600(ActivityThread.java:130) 
                      at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1195) 
                      at android.os.Handler.dispatchMessage(Handler.java:99) 
                      at android.os.Looper.loop(Looper.java:137) 
                      at android.app.ActivityThread.main(ActivityThread.java:4745) 
                      at java.lang.reflect.Method.invokeNative(Native Method) 
                      at java.lang.reflect.Method.invoke(Method.java:511) 
                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:786) 
                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:553) 
                      at dalvik.system.NativeStart.main(Native Method) `

This is the CustomVolley(MyVolley).

```
package com.capstone.artink.app;

import android.content.Context;

import com.android.volley.RequestQueue;
import com.android.volley.toolbox.ImageLoader;
import com.android.volley.toolbox.Volley;
import com.capstone.artink.utils.LruBitmapCache;

public class CustomVolley{

    private static RequestQueue mRequestQueue;
    private static ImageLoader mImageLoader;

    private CustomVolley(){

    }

    static void init(Context context){
        mRequestQueue = Volley.newRequestQueue(context);
        mImageLoader = new ImageLoader(mRequestQueue, new LruBitmapCache());
    }

    public static RequestQueue getRequestQueue(){
        if(mRequestQueue != null){
            return mRequestQueue;
        }
        else { throw new IllegalStateException("RequestQueue Not Initialized"); }
    }

    public static ImageLoader getImageLoader(){
        if(mImageLoader != null){
            return mImageLoader;
        }

        else
        { throw new IllegalStateException("ImageLoader Not Initialized"); }
    }
}
```

This is the error on Dashboard.java line 101

```
RequestQueue queue = CustomVolley.getRequestQueue();

        final String user = username;
        final String type = usertype;

        JsonObjectRequest myRequest = new JsonObjectRequest(Request.Method.GET,
                Config.ENT_PROFILE_URL,
                null,
                RequestSuccessListener(),
                RequestFailedListener()) {

        };
        queue.add(myRequest);
```

I think I posted at the wrong file, it's supposed to be at Act_JsonRequest.java

**Comment by ogrebgr** [comment]
Probably you forgot to call your init() method before calling getRequestQueue()?
